MAKE_HTC_LK := 1
ENABLE_BOOTLOADER_LOG := 1
ENABLE_HTC_REBOOT_INFO_SAVE_IN_EMMC := 1

DEFINES += _MAKE_HTC_LK=1
DEFINES += PROJECT=\"$(PROJECT)\"

MODULES += htc

DEFINES += ENABLE_BOOTLOADER_LOG=$(ENABLE_BOOTLOADER_LOG)

DEFINES += $(HTC_BUILD_MODE)

ifeq ($(HTC_BUILD_MODE), SHIP_BUILD)
ASMFLAGS += -Wa,--defsym,HTC_BUILD_MODE=0
else ifeq ($(HTC_BUILD_MODE), MFG_BUILD)
ASMFLAGS += -Wa,--defsym,HTC_BUILD_MODE=1
else
ASMFLAGS += -Wa,--defsym,HTC_BUILD_MODE=2
endif

$(touch htc/include/htc_version_info.inc)
include htc/tools/htc_git_revision.mk

ifeq ($(ENABLE_HTC_REBOOT_INFO_SAVE_IN_EMMC), 1)
DEFINES += ENABLE_HTC_REBOOT_INFO_SAVE_IN_EMMC
endif

DEFINES += TAMPER_DETECT=$(TAMPER_DETECT)