# Setting ro.sf.lcd_density by lcm height and width if it is not defined
ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),320_240)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=120
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),400_240)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=120
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),432_240)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=120

else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),480_320)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=160
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),640_480)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=160

else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),800_480)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=240
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),854_480)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=240
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),960_540)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=240
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1024_600)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=240

else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1280_720)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=320
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1280_768)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=320
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1024_768)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=320
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1152_768)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=320
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1366_768)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=320
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1280_800)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=320

else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1920_1080)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=480
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),1920_1200)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=480

else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),2048_1152)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=640
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),2560_1440)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=640
else ifeq ($(LCM_HEIGHT)_$(LCM_WIDTH),2560_1600)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.sf.lcd_density=640
endif

